// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("IcedTasks")>]
[<assembly: AssemblyProductAttribute("IcedTasks")>]
[<assembly: AssemblyVersionAttribute("0.10.2")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2024-01-28T00:00:00.0000000-05:00")>]
[<assembly: AssemblyFileVersionAttribute("0.10.2")>]
[<assembly: AssemblyInformationalVersionAttribute("0.10.2")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","release")>]
[<assembly: AssemblyMetadataAttribute("GitHash","bd902a004123985885b43150b85ce46c80c2e082")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "IcedTasks"
    let [<Literal>] AssemblyProduct = "IcedTasks"
    let [<Literal>] AssemblyVersion = "0.10.2"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2024-01-28T00:00:00.0000000-05:00"
    let [<Literal>] AssemblyFileVersion = "0.10.2"
    let [<Literal>] AssemblyInformationalVersion = "0.10.2"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "release"
    let [<Literal>] AssemblyMetadata_GitHash = "bd902a004123985885b43150b85ce46c80c2e082"
