// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("IcedTasks.Tests")>]
[<assembly: AssemblyProductAttribute("IcedTasks")>]
[<assembly: AssemblyVersionAttribute("0.1.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2022-03-06T00:00:00.0000000-05:00")>]
[<assembly: AssemblyFileVersionAttribute("0.1.0")>]
[<assembly: AssemblyInformationalVersionAttribute("0.1.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","beta")>]
[<assembly: AssemblyMetadataAttribute("GitHash","3f298e0afc48e70a5b4097b593f7214df1186de2")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "IcedTasks.Tests"
    let [<Literal>] AssemblyProduct = "IcedTasks"
    let [<Literal>] AssemblyVersion = "0.1.0"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2022-03-06T00:00:00.0000000-05:00"
    let [<Literal>] AssemblyFileVersion = "0.1.0"
    let [<Literal>] AssemblyInformationalVersion = "0.1.0"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "beta"
    let [<Literal>] AssemblyMetadata_GitHash = "3f298e0afc48e70a5b4097b593f7214df1186de2"
