// Auto-Generated by FAKE; do not edit
namespace System

open System.Reflection

[<assembly: AssemblyTitleAttribute("IcedTasks.Tests.NS20")>]
[<assembly: AssemblyProductAttribute("IcedTasks")>]
[<assembly: AssemblyVersionAttribute("0.2.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate", "2022-03-22T00:00:00.0000000-04:00")>]
[<assembly: AssemblyFileVersionAttribute("0.2.0")>]
[<assembly: AssemblyInformationalVersionAttribute("0.2.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel", "release")>]
[<assembly: AssemblyMetadataAttribute("GitHash", "3420057c3dedcf65db053f02aec607cf7f4eee06")>]
do ()

module internal AssemblyVersionInformation =
    [<Literal>]
    let AssemblyTitle = "IcedTasks.Tests"

    [<Literal>]
    let AssemblyProduct = "IcedTasks"

    [<Literal>]
    let AssemblyVersion = "0.2.0"

    [<Literal>]
    let AssemblyMetadata_ReleaseDate = "2022-03-22T00:00:00.0000000-04:00"

    [<Literal>]
    let AssemblyFileVersion = "0.2.0"

    [<Literal>]
    let AssemblyInformationalVersion = "0.2.0"

    [<Literal>]
    let AssemblyMetadata_ReleaseChannel = "release"

    [<Literal>]
    let AssemblyMetadata_GitHash = "3420057c3dedcf65db053f02aec607cf7f4eee06"
