name: Build master

on:
  # Runs only on pushes to the default branch or pull requests to the default branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  # Builds the project for all supported configurations and operating systems
  build:
    strategy:
      matrix:
        # Builds for Debug and Release configurations
        configuration: [Debug, Release]
        # Builds for Ubuntu, Windows, and macOS
        os: [ubuntu-latest, windows-latest, macOS-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup necessary dotnet SDKs
        uses: actions/setup-dotnet@v3
        with:
          global-json-file: global.json
          dotnet-version: |
            8.x
            9.x
      # Build on mac/linux
      - name: Build via Bash
        if: runner.os != 'Windows'
        run: |
          chmod +x ./build.sh
          ./build.sh
        env:
          CONFIGURATION: ${{ matrix.configuration }}
          CI: true
      # Build on windows
      - name: Build via Windows
        if: runner.os == 'Windows'
        run: ./build.cmd
        env:
          CONFIGURATION: ${{ matrix.configuration }}
          CI: true
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Test Results (${{ matrix.os }}-${{ matrix.configuration }})
          path: '**/TestResults/testResults*.trx'
          reporter: dotnet-trx
  # Builds the project in a dev container
  build-devcontainer:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: Build and run dev container task
        uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            chmod +x ./build.sh
            ./build.sh
        env:
          CI: true
