name: .NET Publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup necessary dotnet SDKs
      uses: actions/setup-dotnet@v3
      with:
        global-json-file: global.json
        dotnet-version: |
          2.1.x
          3.1.x
          5.x
          6.x
    - name: publish
      env:
        NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        FAKE_DETAILED_ERRORS: true
      run:  |
        chmod +x ./build.sh
        ./build.sh Publish
